name: Update Docker Hub README

env:
    ACTIONS_ALLOW_UNSECURE_COMMANDS: true
on:
  push:
    branches: [ 'master' ]
    paths:
      - README.md
      - '.github/workflows/update-readme.yml'

jobs:
  sync:
    name: Update README to Docker Hub
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: lnliz/bitcoind
